create table if not exists public.stores (
  kakao_place_id text primary key,
  slug text unique not null,
  name text not null,
  category text,
  phone text,
  address text,
  road_address text,
  latitude text,
  longitude text,
  kakao_url text not null,
  instagram_url text,
  region text,
  search_keyword text,
  menu_check_status text default 'unchecked',
  menu_evidence text,
  translation_status text default 'not-started',
  publish_status text default 'draft',
  checked_at timestamptz,
  updated_at timestamptz default now()
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  kakao_place_id text not null references public.stores(kakao_place_id) on delete cascade,
  menu_id text not null,
  sort_order integer default 0,
  category text,
  name_ko text not null,
  description_ko text,
  price text,
  is_representative boolean default false,
  name_en text,
  description_en text,
  name_ja text,
  description_ja text,
  unique(kakao_place_id, menu_id)
);

alter table public.stores enable row level security;
alter table public.menus enable row level security;

create policy "Public can read published stores"
on public.stores for select
using (publish_status = 'published');

create policy "Public can read menus of published stores"
on public.menus for select
using (exists (
  select 1 from public.stores
  where stores.kakao_place_id = menus.kakao_place_id
  and stores.publish_status = 'published'
));
