import type { StoreRecord } from "./types";

export const DEMO_STORE: StoreRecord = {
  kakaoPlaceId: "demo-standard-bread",
  slug: "standard-bread-seongsu",
  name: "스탠다드브레드 성수",
  category: "제과·베이커리",
  phone: "",
  address: "서울 성동구 성수동2가",
  roadAddress: "서울 성동구 성수이로18길 37 1층",
  latitude: "37.5448",
  longitude: "127.0642",
  kakaoUrl: "https://map.kakao.com/",
  instagramUrl: "https://www.instagram.com/standardbread_official/",
  region: "성수",
  searchKeyword: "베이커리",
  menuCheckStatus: "found",
  menuEvidence: "카카오맵 텍스트 메뉴와 메뉴판 사진이 함께 등록된 샘플",
  translationStatus: "reviewed",
  publishStatus: "published",
  checkedAt: "2026-07-14T00:00:00.000Z",
  updatedAt: "2026-07-14T00:00:00.000Z",
  menus: [
    {
      id: "menu-1",
      category: "Toast",
      nameKo: "크림브륄레 프렌치 토스트",
      descriptionKo: "겉은 바삭하고 속은 촉촉한 커스터드 크림 프렌치 토스트",
      price: "13,000원",
      isRepresentative: true,
      nameEn: "Crème Brûlée French Toast",
      descriptionEn: "Crisp outside, soft inside, finished with rich custard cream.",
      nameJa: "クレームブリュレ・フレンチトースト",
      descriptionJa: "外はカリッと、中はしっとり。濃厚なカスタードクリームのフレンチトーストです。",
    },
    {
      id: "menu-2",
      category: "Toast",
      nameKo: "메이플 베이컨 피스타치오 토스트",
      descriptionKo: "메이플시럽, 베이컨, 피스타치오가 어우러진 단짠 토스트",
      price: "14,900원",
      isRepresentative: true,
      nameEn: "Maple Bacon Pistachio Toast",
      descriptionEn: "Soft toast topped with maple syrup, savory bacon and pistachios.",
      nameJa: "メープルベーコン・ピスタチオトースト",
      descriptionJa: "メープルシロップ、ベーコン、ピスタチオを合わせた甘じょっぱいトーストです。",
    },
    {
      id: "menu-3",
      category: "Coffee",
      nameKo: "스탠다드슈패너",
      descriptionKo: "부드러운 크림을 올린 시그니처 커피",
      price: "6,800원",
      isRepresentative: false,
      nameEn: "Standard Einspänner",
      descriptionEn: "Signature coffee topped with smooth cream.",
      nameJa: "スタンダード・アインシュペナー",
      descriptionJa: "なめらかなクリームをのせたシグネチャーコーヒーです。",
    },
  ],
};
