create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  session_id uuid not null,
  event_name text not null check (event_name in ('page_view', 'search', 'store_select')),
  page_path text not null default '/',
  language text check (language is null or language in ('en', 'ja')),
  search_query text,
  region text,
  category text,
  result_count integer check (result_count is null or result_count >= 0),
  store_id text,
  store_name text,
  created_at timestamp with time zone not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_event_name_created_at_idx
  on public.analytics_events (event_name, created_at desc);

create index if not exists analytics_events_visitor_id_created_at_idx
  on public.analytics_events (visitor_id, created_at desc);

create index if not exists analytics_events_search_query_idx
  on public.analytics_events (search_query)
  where search_query is not null;

alter table public.analytics_events enable row level security;

revoke all on table public.analytics_events from anon, authenticated;
revoke all on sequence public.analytics_events_id_seq from anon, authenticated;
